add new achievemens - new branch for achievements 2024
PiechZ/greybox_wrapped pull request #101
Opened 2024-04-14 09:06 UTC by PiechZ

Please review my new achievements.

2024-04-14 09:29 UTC, shippy requested changes
Question about the use of ANY_VALUE (I think that could kill some achievements at the end of achievements__final given the school year limitation - if anything, MAX might make more sense) + I assume I should make the images?

2024-04-14 09:29 UTC, shippy commented on sql_prep/models/achievements/agg__napul_cesty.sql
> +        ANY_VALUE(school_year) as school_year,
Why the ANY_VALUE? Wouldn't it make sense to skip it altogether if you don't want to aggregate by it?

2024-04-14 11:35 UTC, PiechZ reviewed
I fixed these two achievements according to your advice.

2024-05-05 21:37 UTC, shippy commented
Fun fact: Windows and Unix are different in that one is case-sensitive (Unix) and the other is not (Windows). So I'm guessing the capital-letters name doesn't make a difference on Windows in terms of `ref`, but does on Unix/MacOS.

2024-05-18 22:46 UTC, merged